name: renovate-config-validator

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/vaidate-renovate-config.yml
      - default.json
      - renovate.json
  push:
    branches:
      - main
    paths:
      - .github/workflows/vaidate-renovate-config.yml
      - default.json
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
        with:
          config_file_path: default.json
          strict: true
